Repository softeerbootcamp-3nd/softee5-samchi-BE, pull requests merged in 2024-01, with the labels that each got.

#1 Feat/domain : ERD 설계에 따른 엔티티 추가 작업 완료
  src/main/java/ssamchi/softeer/drivechat/controller/HelloController.java
  src/main/java/ssamchi/softeer/drivechat/domain/BaseEntity.java
  src/main/java/ssamchi/softeer/drivechat/domain/Driver.java
  src/main/java/ssamchi/softeer/drivechat/domain/Guest.java
  src/main/java/ssamchi/softeer/drivechat/domain/Match.java
  src/main/java/ssamchi/softeer/drivechat/domain/PickTopic.java
  src/main/java/ssamchi/softeer/drivechat/domain/Topic.java
  src/main/java/ssamchi/softeer/drivechat/domain/User.java
  src/main/java/ssamchi/softeer/drivechat/domain/UserType.java
  src/main/resources/application.properties
Labels: 💻Develope💻

#2 [메인 맵 관련 API 3개 작업 완료]
  src/main/java/ssamchi/softeer/drivechat/DrivechatApplication.java
  src/main/java/ssamchi/softeer/drivechat/controller/MainMapController.java
  src/main/java/ssamchi/softeer/drivechat/domain/Driver.java
  src/main/java/ssamchi/softeer/drivechat/domain/DriverTopic.java
  src/main/java/ssamchi/softeer/drivechat/domain/Guest.java
  src/main/java/ssamchi/softeer/drivechat/domain/GuestTopic.java
  src/main/java/ssamchi/softeer/drivechat/domain/Topic.java
  src/main/java/ssamchi/softeer/drivechat/domain/UserType.java
  src/main/java/ssamchi/softeer/drivechat/dto/request/RequestDriverMarkerMakeDto.java
  src/main/java/ssamchi/softeer/drivechat/dto/response/DriverMarkerDetailInfoResponseDto.java
  src/main/java/ssamchi/softeer/drivechat/dto/response/MainMapMarkerIdListResponseDto.java
  src/main/java/ssamchi/softeer/drivechat/dto/response/ResponseDriverMarkerMakeDto.java
  src/main/java/ssamchi/softeer/drivechat/exception/Error.java
  src/main/java/ssamchi/softeer/drivechat/repository/DriverRepository.java
  src/main/java/ssamchi/softeer/drivechat/repository/DriverTopicRepository.java
  src/main/java/ssamchi/softeer/drivechat/repository/GuestRepository.java
  src/main/java/ssamchi/softeer/drivechat/repository/UserRepository.java
  src/main/java/ssamchi/softeer/drivechat/service/MarkerService.java
  src/main/java/ssamchi/softeer/drivechat/utils/HeaderUtils.java
  src/main/java/ssamchi/softeer/drivechat/utils/ServletUtils.java
Labels: 💻Develope💻

#5 [Swaager Config 추가]
  build.gradle
  src/main/java/ssamchi/softeer/drivechat/config/SwaggerConfig.java
  src/main/java/ssamchi/softeer/drivechat/controller/MatchController.java
  src/main/java/ssamchi/softeer/drivechat/controller/TopicController.java
  src/main/java/ssamchi/softeer/drivechat/domain/Driver.java
  src/main/java/ssamchi/softeer/drivechat/domain/Match.java
  src/main/java/ssamchi/softeer/drivechat/dto/request/ConversationRequestDto.java
  src/main/java/ssamchi/softeer/drivechat/dto/request/DriverTopicRequestDTO.java
  src/main/java/ssamchi/softeer/drivechat/dto/request/GuestTopicRequestDTO.java
  src/main/java/ssamchi/softeer/drivechat/dto/response/SummaryResponseDto.java
  src/main/java/ssamchi/softeer/drivechat/dto/response/TopicResponseDTO.java
  src/main/java/ssamchi/softeer/drivechat/exception/Error.java
  src/main/java/ssamchi/softeer/drivechat/repository/DriverRepository.java
  src/main/java/ssamchi/softeer/drivechat/repository/GuestRepository.java
  src/main/java/ssamchi/softeer/drivechat/repository/GuestTopicRepository.java
  src/main/java/ssamchi/softeer/drivechat/repository/MatchRepository.java
  src/main/java/ssamchi/softeer/drivechat/repository/TopicRepository.java
  src/main/java/ssamchi/softeer/drivechat/service/DriverTopicService.java
  src/main/java/ssamchi/softeer/drivechat/service/GuestTopicService.java
  src/main/java/ssamchi/softeer/drivechat/service/MatchService.java
  src/main/java/ssamchi/softeer/drivechat/service/TopicService.java
Labels: 💻Develope💻

#7 [Matching API]
  src/main/java/ssamchi/softeer/drivechat/controller/MatchController.java
  src/main/java/ssamchi/softeer/drivechat/dto/request/RequestMakeMatchingDto.java
  src/main/java/ssamchi/softeer/drivechat/dto/request/RequestMatchCheckDto.java
  src/main/java/ssamchi/softeer/drivechat/dto/response/ResponseMakeMatchingDto.java
  src/main/java/ssamchi/softeer/drivechat/dto/response/ResponseMatchCheckDto.java
  src/main/java/ssamchi/softeer/drivechat/repository/DriverRepository.java
  src/main/java/ssamchi/softeer/drivechat/service/MatchService.java
Labels: 💻Develope💻

#9 :art: Fix : 드라이브 챗 시작하기 API 수정 (DTO, 비지니스 로직)
  src/main/java/ssamchi/softeer/drivechat/controller/MainMapController.java
  src/main/java/ssamchi/softeer/drivechat/dto/common/UserType.java
  src/main/java/ssamchi/softeer/drivechat/dto/request/DriverChatRegistrationRequestDto.java
  src/main/java/ssamchi/softeer/drivechat/dto/response/DriveChatRegistrationResponseDto.java
  src/main/java/ssamchi/softeer/drivechat/dto/response/ResponseDriverMarkerMakeDto.java
  src/main/java/ssamchi/softeer/drivechat/repository/TopicRepository.java
  src/main/java/ssamchi/softeer/drivechat/service/MarkerService.java
Labels: 💻Develope💻, 📣BugFix📢

#10 [동승 요청 API 추가]
  src/main/java/ssamchi/softeer/drivechat/controller/MatchController.java
  src/main/java/ssamchi/softeer/drivechat/domain/Match.java
  src/main/java/ssamchi/softeer/drivechat/dto/request/BoardRequestRequestDto.java
  src/main/java/ssamchi/softeer/drivechat/dto/response/BoardRequestResponseDto.java
  src/main/java/ssamchi/softeer/drivechat/exception/Error.java
  src/main/java/ssamchi/softeer/drivechat/service/DriverTopicService.java
  src/main/java/ssamchi/softeer/drivechat/service/MarkerService.java
  src/main/java/ssamchi/softeer/drivechat/service/MatchService.java
Labels: 💻Develope💻

#16 [Swagger description 추가 및 자잘한 코드 수정]
  src/main/java/ssamchi/softeer/drivechat/config/CorsConfig.java
  src/main/java/ssamchi/softeer/drivechat/controller/MainMapController.java
  src/main/java/ssamchi/softeer/drivechat/controller/MatchController.java
  src/main/java/ssamchi/softeer/drivechat/controller/ReviewController.java
  src/main/java/ssamchi/softeer/drivechat/controller/TopicController.java
  src/main/java/ssamchi/softeer/drivechat/controller/UserController.java
  src/main/java/ssamchi/softeer/drivechat/domain/Match.java
  src/main/java/ssamchi/softeer/drivechat/dto/request/RequestConfirmMatchingDto.java
  src/main/java/ssamchi/softeer/drivechat/dto/request/RequestGuestInfoDto.java
  src/main/java/ssamchi/softeer/drivechat/dto/request/RequestMakeMatchingDto.java
  src/main/java/ssamchi/softeer/drivechat/dto/request/test.txt
  src/main/java/ssamchi/softeer/drivechat/dto/response/FilteredMarkerIdListResponseDto.java
  src/main/java/ssamchi/softeer/drivechat/dto/response/ResponseConfirmMatchingDto.java
  src/main/java/ssamchi/softeer/drivechat/dto/response/ResponseDriverInfoDto.java
  src/main/java/ssamchi/softeer/drivechat/dto/response/ResponseGuestInfoDto.java
  src/main/java/ssamchi/softeer/drivechat/dto/response/test1.txt
  src/main/java/ssamchi/softeer/drivechat/exception/Error.java
  src/main/java/ssamchi/softeer/drivechat/repository/GuestRepository.java
  src/main/java/ssamchi/softeer/drivechat/service/MarkerService.java
  src/main/java/ssamchi/softeer/drivechat/service/MatchService.java
  src/main/java/ssamchi/softeer/drivechat/service/UserService.java
Labels: 📣BugFix📢
